#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#	contains the string 'Hello World'
#	listens on port 80

apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html

service nginx restart
