#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#	Index page contains the string 'Hello World'
#	listens on port 80
#	A 301 redirect
#	A 404 redirect page with message

apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
touch /etc/nginx/html/404.html

echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 http://josaya.tech/;
    }
    error_page 404 /404.html;
    location /404 {
      root /etc/nginx/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
