#!/usr/bin/env bash

# Installs HAProxy load balancer
# Uses the roundrobin algorithm
# Can be managed via an init script

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get install haproxy=2.6.\*

printf %s "backend web-backend
	balance roundrobin
	server 105686-web-01 54.165.148.10:80 check
	server 105686-web-02 54.175.25.248:80 check
	" > /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
