#!/usr/bin/env bash
# Indefinitely writes "I am alive" to the file /tmp/my_process.
#  Pauses for two seconds in between each message.

while true
do
  
  read -t 2 -p "I am alive!" >> /tmp/my_process 
done
