#!/usr/bin/env bash
# Blocks all ports and opens only TCP ports 22, 443 and 80.

sudo apt-get install ufw

sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
