#!/usr/bin/env bash
# configures nginx to run as nginx user on port 8080

sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
echo -e "\n" "$0"

